version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    networks:
      - internal-net
    environment:
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: express-backend
    expose:
      - "5000"
    networks:
      - internal-net

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge
